Models/Quote.cs
namespace RevisioneNew.Models
{
    public class Quote
    {
        public Guid QuoteId { get; set; }
        public string QuoteNumber { get; set; }
        public string QuoteName { get; set; }
        public decimal TotalAmount { get; set; }
        public DateTime ExpirationDate { get; set; }
        public DateTime CreatedOn { get; set; }
        public string Status { get; set; } // Draft, Active, Closed, etc.
        public string Statuscode { get; set; } // Draft, Active, Closed, etc.

        // Foreign Keys
        public Guid OpportunityId { get; set; }
        public OpportunityModel Opportunity { get; set; }
    }
}

Controllers/QuoteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Xrm.Sdk;
using System.Linq.Dynamic.Core;
using RevisioneNew.Models;
using Microsoft.PowerPlatform.Dataverse.Client;
using RevisioneNew.Interfaces;
using RevisioneNew.Services;

namespace RevisioneNew.Controllers
{
    public class QuoteController : Controller
    {
        private readonly ServiceClient _serviceClient;
        private readonly IServiceInterface _service;
        private readonly IQuoteInterface _quoteService;
            List<Quote> quoteList = new List<Quote>();

        public QuoteController(ServiceClient serviceClient, IServiceInterface service,IQuoteInterface quoteService)
        {
            _service = service;
            _serviceClient = serviceClient;
            _quoteService = quoteService;
            QueryExpression queryExpression = new QueryExpression("quote")
            {
                ColumnSet = new ColumnSet("name", "totalamount", "statecode", "createdon","quotenumber", "statuscode")
            };
            EntityCollection quotes = _serviceClient.RetrieveMultiple(queryExpression);

            foreach (var item in quotes.Entities)
            {
                quoteList.Add(new Quote
                {
                    QuoteNumber = item.GetAttributeValue<string>("quotenumber"),
                    QuoteName = item.GetAttributeValue<string>("name"),
                    TotalAmount = item.GetAttributeValue<Money>("totalamount").Value,
                    Status = ((QuoteStateCode)item.GetAttributeValue<OptionSetValue>("statecode").Value).ToString(),
                    CreatedOn = item.GetAttributeValue<DateTime>("createdon"),
                    QuoteId = item.GetAttributeValue<Guid>("quoteid"),
                    Statuscode = ((QuoteStatusCode)item.GetAttributeValue<OptionSetValue>("statuscode").Value).ToString()
                });
            }
        }

        [HttpPost]
        public JsonResult LoadQuoteList()
        {
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                PagingInfo pagingInfo = new PagingInfo()
                {
                    Count = pageSize,
                    PageNumber = (skip/pageSize)+1,
                    ReturnTotalRecordCount =true
                };
                Datatable<Quote> QuoteData = _quoteService.getQuoteData(draw, sortColumn, pagingInfo, searchValue,sortColumnDirection); 

                return Json(QuoteData);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult CloseQuote(string quoteID, string quoteNumber)
        {
            try
            {  
                if (quoteID != null)
                {
                    Guid quoteGuid = new(quoteID);

                    CloseQuoteRequest closeQuoteRequest = new CloseQuoteRequest();
                    closeQuoteRequest.QuoteClose = new Entity("quoteclose")
                    {
                        Attributes =
                        {
                            {"subject",$"Quote Closed (Lost) - {quoteNumber}" },
                            { "quoteid", new EntityReference("quote", quoteGuid) }
                        }
                    };
                    closeQuoteRequest.Status = new OptionSetValue((int)QuoteStatusCode.Lost);
                    _serviceClient.Execute(closeQuoteRequest);

                    return Ok($"Quote is successfully Lost.");
                }
                return BadRequest("Quote not found");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult WinQuote (string quoteID, string quoteNumber)
        {
            try
            {
                if (quoteID != null)
                {
                    Guid quoteGuid = new(quoteID);

                    //WinQuoteRequest winQuoteRequest = new()
                    //{
                    //    QuoteClose = new Entity("quoteclose")
                    //    {
                    //        Attributes =
                    //        {
                    //            {"subject", $"Quote Won (Won) - {quoteNumber}" },
                    //            { "quoteid", new EntityReference("quote", quoteGuid) }
                    //        }
                    //    },
                    //    Status = new OptionSetValue(-1)
                    //};
                    //_serviceClient.Execute(winQuoteRequest);

                    ConvertQuoteToSalesOrderRequest convertQuoteToSalesOrderRequest = new ConvertQuoteToSalesOrderRequest()
                    {
                        QuoteId = quoteGuid,
                        ColumnSet = new ColumnSet("name", "ordernumber"),
                        QuoteCloseStatus = new OptionSetValue(-1),
                        QuoteCloseSubject= $"Quote Won (Won) - {quoteNumber}",
                        QuoteCloseDate =DateTime.Now
                    };
                    ConvertQuoteToSalesOrderResponse convertQuoteToSalesOrderResponse = (ConvertQuoteToSalesOrderResponse)_serviceClient.Execute(convertQuoteToSalesOrderRequest);
                    return Ok($"Quote is successfully Won and Order created with oreder-number : " + convertQuoteToSalesOrderResponse.Entity.GetAttributeValue<string>("ordernumber"));
                }
                return BadRequest("Quote not found");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult ActiveQuote(string quoteID)
        {
            try
            {
                if (quoteID != null)
                {
                    Guid quoteGuid = new Guid(quoteID);

                    SetStateRequest activateQuote = new SetStateRequest()
                    {
                        EntityMoniker = new EntityReference("quote",quoteGuid),
                        State = new OptionSetValue((int)QuoteStateCode.Active),
                        Status = new OptionSetValue((int)QuoteStatusCode.InProgress_Active) //in progress
                    };
                    _serviceClient.Execute(activateQuote);
                    return Ok("Quote is successfully Activated.");

                    //return BadRequest("Order creation failed.");
                }
                return BadRequest("Quote not found");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public IActionResult ReviseQuote(string quoteID)
        {
            try
            {
                string reviseQuoteNumber = _quoteService.RevisedQuoteService(quoteID);
                if(reviseQuoteNumber != null)
                {
                    return Ok($"Revised Quote created with Quote number: {reviseQuoteNumber}");
                }
                return BadRequest("There is some error occured");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        public IActionResult DeleteQuote(string quoteID)
        {
            try
            {
                if(quoteID != null)
                {
                    Guid quoteGuid = new Guid(quoteID);
                    _service.Delete("quote", quoteGuid);
                    return Ok("Data deleted successfully.");
                }
                return BadRequest("Quote is not found.");
            }
            catch (Exception ex)
            {

                return BadRequest(ex.Message);
            }

        }

        [Route("/Quotes")]
        public IActionResult Quotes()
        {
            ViewBag.Quote = "active";
            return View();
        }
    }
}

Views/Quote/Quotes.cshtml
<main>
    <div class="section-header">
        <h1>Quotes</h1>
    </div>
    <div class="section-body">
        <table class="table table-bordered" id="table-1" style="width:100%">
            <thead clas>
                <tr>
                    <th>Quote Number</th>
                    <th>Quote Name</th>
                    <th>TotalAmount</th>
                    <th>Status</th>
                    <th>Created On</th>
                    <th>Actions</th>
                </tr>
            </thead>
        </table>
    </div>
</main>




@section Scripts{

    <script src="~/assets/modules/datatables/datatables.min.js"></script>
    <script src="~/assets/modules/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/assets/modules/datatables/Select-1.2.4/js/dataTables.select.min.js"></script>
    <script src="~/assets/modules/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/assets/modules/sweetalert/sweetalert.min.js"></script>
    <script src="~/assets/modules/izitoast/js/iziToast.min.js"></script>

    <script>
        let opportunityTable;
        $(document).ready(function () {
            opportunityTable = $("#table-1").DataTable({
                "processing": true,
                "serverSide": true,
                //"bStateSave":true,
                "filter": true,
                "ajax": {
                    "url": "/Quote/LoadQuoteList",
                    "type": "POST",
                    "datatype": "json",
                },
                "columnDefs": [{
                    "targets": [2,3],
                    searchable: false
                }, {
                        "targets": [5],
                    searchable: false,
                    orderable: false
                    }],
                "columns": [
                    { "data": "quoteNumber", "name": "quotenumber", "autoWidth": true },
                    { "data": "quoteName", "name": "name", "autoWidth": true },
                    {
                        "data": "totalAmount", "name": "totalamount", "autoWidth": true,
                        render: function (data) {
                            if (data == null) {
                                return `<b>Amount is not available</b>`
                            }
                            else {
                                return `$ ${parseFloat(data).toFixed(2)}`;
                            }
                        }
                    },
                    {
                        "data": "status", "name": "statecode", "autoWidth": true,
                        render: function (data) {
                            if (data == '@QuoteStateCode.Draft.ToString()')
                            {
                                return `<div class="badge badge-warning">${data}</div>`
                            }
                            else if (data == '@QuoteStateCode.Active.ToString()')
                            {
                                return `<div class="badge badge-info">${data}</div>`
                            }
                            else if (data == '@QuoteStateCode.Closed.ToString()')
                            {
                                return `<div class="badge badge-danger">${data}</div>`
                            }
                             else if (data == '@QuoteStateCode.Won.ToString()')
                             {
                                 return `<div class="badge badge-success">${data}</div>`
                             }
                        }
                    },
                    {
                        "data": "createdOn", "name": "createdon", "autoWidth": true,
                        render: function (data) {
                            let date = new Date(data.split('T')[0]);
                            return date.toLocaleDateString('en-GB')
                        }
                    },
                    {
                        render: function (data, type, full, meta) {
                            let ReturnHtml = `<div class="w-100 d-flex justify-content-center">
                                <button class="btn btn-primary mx-2" onclick="TostExample('${full.quoteId}')" data-toggle="tooltip" data-original-title="Quote information"><i class="fas fa-eye"></i></button>`
                            if (full.status == '@QuoteStateCode.Draft.ToString()') {
                                ReturnHtml += `<button class="btn btn-info mx-2" onclick="activateQuote('${full.quoteId}')" data-toggle="tooltip" data-original-title="ActivateQuote"><i class="fas fa-file-alt"></i></button>`
                            }
                            if (full.status == '@QuoteStateCode.Closed.ToString()') {
                                ReturnHtml += `<button class="btn btn-info mx-2" onclick="reviseQuote('${full.quoteId}')" data-toggle="tooltip" data-original-title="Revise Quote"><i class="fas fa-file-signature"></i></button>`
                            }
                            if (full.status == '@QuoteStateCode.Active.ToString()') {
                                ReturnHtml += `<button class="btn btn-warning mx-2" onclick="winQuote('${full.quoteId}','${full.quoteNumber}')" data-toggle="tooltip" data-original-title="Won Quote Create Order"><i class="fas fa-check"></i></button><button class="btn btn-danger mx-2" onclick="quoteCloseasLost('${full.quoteId}','${full.quoteNumber}')" data-toggle="tooltip" data-original-title="Close Quote as Lost"><i class="fas fa-times"></i></button>`
                            }
                            ReturnHtml += `
                                <button class="btn btn-dark mx-2" onclick="deleteQuote('${full.quoteId}','${full.quoteNumber}')" data-toggle="tooltip" data-original-title="Quote information"><i class="fas fa-trash"></i></button>`
                            return ReturnHtml
                        }
                    }
                ]
            });
            $(document).ajaxComplete(function () {
                // Required for Bootstrap tooltips in DataTables
                $('[data-toggle="tooltip"]').tooltip({
                    "html": true,
                    "delay": { "show": 100, "hide": 0 },
                });
            });
        });
        function winQuote(id,number) {
            $('#mainscreen').show();
            $(document.body).addClass('no-scroll');
                $.ajax({
                    url: '@Url.Action("WinQuote","Quote")',
                    data: { quoteID: id, quoteNumber: number },
                    type: "Post",
                    success: (r) => {
                        $('#mainscreen').hide();
                        $(document.body).removeClass('no-scroll');
                        iziToast.success({
                            title: 'Success :',
                            message: r,
                            position: 'topRight'
                        });
                        opportunityTable.ajax.reload(null,false);
                    },
                    error: (r) => {
                        debugger
                        $('#mainscreen').hide();
                        $(document.body).removeClass('no-scroll');
                        if (r.status == 400) {
                            iziToast.error({
                                title: 'Error :',
                                message: r.responseText,
                                position: 'topRight'
                            });
                        }
                    }
                })
        }

        function quoteCloseasLost(id,number) {
            $('#mainscreen').show();
            $(document.body).addClass('no-scroll')
            Taskid = id

            $.ajax({
                url: '@Url.Action("CloseQuote", "Quote")',
                data: { quoteID: id, quoteNumber: number },
                type: "Post",
                success: (r) => {
                    debugger
                    $('#mainscreen').hide();
                    $(document.body).removeClass('no-scroll');
                    iziToast.success({
                        title: 'Success :',
                        message: r,
                        position: 'topRight'
                    });
                    opportunityTable.ajax.reload(null, false);
                },
                error: (r) => {
                    $('#mainscreen').hide();
                    $(document.body).removeClass('no-scroll');
                    debugger
                    if (r.status == 400) {
                        iziToast.error({
                            title: 'Error :',
                            message: r.responseText,
                            position: 'topRight'
                        });
                    }
                }
            })
        }

        function activateQuote(id) {
            $('#mainscreen').show();
            $(document.body).addClass('no-scroll')

            $.ajax({
                url: '@Url.Action("ActiveQuote", "Quote")',
                data: { quoteID: id},
                type: "Post",
                success: (r) => {
                    debugger
                    $('#mainscreen').hide();
                    $(document.body).removeClass('no-scroll');
                    iziToast.success({
                        title: 'Success :',
                        message: r,
                        position: 'topRight'
                    });
                    opportunityTable.ajax.reload(null, false);
                },
                error: (r) => {
                    $('#mainscreen').hide();
                    $(document.body).removeClass('no-scroll');
                    debugger
                    if (r.status == 400) {
                        iziToast.error({
                            title: 'Error :',
                            message: r.responseText,
                            position: 'topRight'
                        });
                    }
                }
            })
        }

        function reviseQuote(id) {
            $('#mainscreen').show();
            $(document.body).addClass('no-scroll')

            $.ajax({
                url: '@Url.Action("ReviseQuote", "Quote")',
                data: { quoteID: id},
                type: "Post",
                success: (r) => {
                    //debugger
                    $('#mainscreen').hide();
                    $(document.body).removeClass('no-scroll');
                    iziToast.success({
                        title: 'Success :',
                        message: r,
                        position: 'topRight'
                    });
                    opportunityTable.ajax.reload(null, false);
                },
                error: (r) => {
                    $('#mainscreen').hide();
                    $(document.body).removeClass('no-scroll');
                    //debugger
                    if (r.status == 400) {
                        iziToast.error({
                            title: 'Error :',
                            message: r.responseText,
                            position: 'topRight'
                        });
                    }
                }
            })
        }

        function deleteQuote(id,quotenumber) {
            swal({
                title: 'Are you sure?',
                text: 'Are you sure you want to delete this quote?',
                icon: 'warning',
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $('#mainscreen').show();
                        $(document.body).addClass('no-scroll')
                        $.ajax({
                            url: '@Url.Action("DeleteQuote", "Quote")',
                            data: { quoteID: id},
                            type: "Post",
                            success: (r) => {
                                //debugger
                                $('#mainscreen').hide();
                                $(document.body).removeClass('no-scroll');
                                iziToast.success({
                                    title: 'Success :',
                                    message: r,
                                    position: 'topRight'
                                });
                                opportunityTable.ajax.reload(null, false);
                            },
                            error: (r) => {
                                $('#mainscreen').hide();
                                $(document.body).removeClass('no-scroll');
                                //debugger
                                if (r.status == 400) {
                                    iziToast.error({
                                        title: 'Error :',
                                        message: r.responseText,
                                        position: 'topRight'
                                    });
                                }
                            }
                        })
                    }
                });

        }

        function TostExample(id) {
            iziToast.success({
                theme: 'dark',
                backgroundColor: 'rgb(75, 175, 39)',
                progressBarColor: 'rgb(0, 132, 0)',
                title: 'success :',
                message: id,
                position: 'topRight'
            });


        }
    </script>
}   